Repository palzo/sandamso, pull requests merged in 2023-11, with the labels that each got.

#81 [로그인 페이지] 자동 로그인, 이메일 유지 기능
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/sansaninfo/GlobalApplication.kt
  app/src/main/java/com/example/sansaninfo/MyPage/MyPageFragment.kt
  app/src/main/java/com/example/sansaninfo/SearchPage/SearchPageMountainFragment.kt
  app/src/main/java/com/example/sansaninfo/SignPage/SignInActivity.kt
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/values/strings.xml
Labels: feature

#83 Bugfix/addpage
  app/src/main/java/com/example/sansaninfo/AddPage/AddPageActivity.kt
Labels: bug_fix

#84 [FEAT] : ⚙️ 삭제하기
  app/src/main/java/com/example/sansaninfo/AddPage/AddPageActivity.kt
  app/src/main/java/com/example/sansaninfo/CommunityPage/CommunityPageFragment.kt
  app/src/main/java/com/example/sansaninfo/DetailPage/DetailPageActivity.kt
  app/src/main/res/drawable/alert_triangle.xml
Labels: feature

#86 [Info-page] 좌표값에 따른 날씨 온도 출력하기
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/src/main/java/com/example/sansaninfo/API/ModelData/RegionLocation.kt
  app/src/main/java/com/example/sansaninfo/API/ModelData/WeatherModel.kt
  app/src/main/java/com/example/sansaninfo/InfoPage/InfoPage.kt
  app/src/main/java/com/example/sansaninfo/InfoPage/InfoPageAdapter.kt
  app/src/main/java/com/example/sansaninfo/InfoPage/RegionLocation.kt
  app/src/main/java/com/example/sansaninfo/SearchPage/GooData.kt
  app/src/main/res/layout/activity_info_page.xml
  app/src/main/res/layout/weather_item.xml
  app/src/main/res/values/strings.xml
Labels: feature, design

#87 [InfoPage] 네이버지도 추가
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sansaninfo/InfoPage/InfoPage.kt
  app/src/main/res/layout/activity_info_page.xml
  settings.gradle
Labels: feature

#91 feature - naver map marker, badwordfiltering
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/com/example/sansaninfo/InfoPage/InfoPage.kt
  app/src/main/java/com/example/sansaninfo/MyPage/ChangeNicknameActivity.kt
  app/src/main/java/com/example/sansaninfo/SignPage/SignInActivity.kt
  app/src/main/java/com/example/sansaninfo/SignPage/SignUpActivity.kt
  app/src/main/java/com/example/sansaninfo/SplashScreen.kt
Labels: feature

#92 [Info-page] 날씨 조건에 따른 날씨 아이콘 변경
  app/src/main/java/com/example/sansaninfo/InfoPage/InfoPage.kt
  app/src/main/java/com/example/sansaninfo/InfoPage/InfoPageAdapter.kt
  app/src/main/java/com/example/sansaninfo/InfoPage/RegionLocation.kt
  app/src/main/java/com/example/sansaninfo/InfoPage/SkyData.kt
  app/src/main/res/drawable/ic_weather_cloudy.png
  app/src/main/res/drawable/ic_weather_lotsclouds.png
  app/src/main/res/drawable/ic_weather_rainy.png
  app/src/main/res/drawable/ic_weather_rainysnow.png
  app/src/main/res/drawable/ic_weather_shower.png
  app/src/main/res/drawable/ic_weather_snow.png
  app/src/main/res/drawable/ic_weather_sunny.png
  app/src/main/res/layout/weather_item.xml
Labels: feature, design

#95 Feature/addpage
  app/src/main/java/com/example/sansaninfo/AddPage/AddPageActivity.kt
  app/src/main/java/com/example/sansaninfo/CommunityPage/CommunityPageFragment.kt
  app/src/main/java/com/example/sansaninfo/DetailPage/DetailPageActivity.kt
  app/src/main/res/layout/activity_add_page.xml
Labels: bug_fix, feature

#97 [UI] : 채팅 화면 추가
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sansaninfo/Chatting/ChattingListAdapter.kt
  app/src/main/java/com/example/sansaninfo/Chatting/ChattingListFragment.kt
  app/src/main/java/com/example/sansaninfo/Chatting/ChattingModel.kt
  app/src/main/java/com/example/sansaninfo/Chatting/ChattingPage.kt
  app/src/main/java/com/example/sansaninfo/Main/MainViewPagerAdapter.kt
  app/src/main/res/drawable/ic_chat.xml
  app/src/main/res/layout/activity_chatting_page.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/chatting_list_item.xml
  app/src/main/res/layout/fragment_chatting_list.xml
  app/src/main/res/menu/tabs.xml
  app/src/main/res/values/strings.xml
Labels: design

#101 [feature] community, add, detail page
  app/src/main/java/com/example/sansaninfo/AddPage/AddPageActivity.kt
  app/src/main/java/com/example/sansaninfo/CommunityPage/CommunityPageFragment.kt
  app/src/main/java/com/example/sansaninfo/DetailPage/DetailPageActivity.kt
  app/src/main/res/layout/activity_add_page.xml
  app/src/main/res/layout/activity_detail_page.xml
Labels: feature

#103 [AllPages, MyPage]
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sansaninfo/InfoPage/InfoPage.kt
  app/src/main/java/com/example/sansaninfo/MyPage/ChangeNicknameActivity.kt
  app/src/main/java/com/example/sansaninfo/MyPage/MyPageFragment.kt
  app/src/main/res/layout/activity_add_page.xml
  app/src/main/res/layout/activity_info_page.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_community_page.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_search_page_mountain.xml
Labels: feature, design

#104 Feature/communitypage option
  app/src/main/java/com/example/sansaninfo/CommunityPage/CommunityPageFragment.kt
  app/src/main/res/drawable/ic_cloud.xml
  app/src/main/res/drawable/ic_community_option.xml
  app/src/main/res/drawable/ic_heavyrain.xml
  app/src/main/res/drawable/ic_sunny.xml
  app/src/main/res/drawable/ic_thunder.xml
  app/src/main/res/layout/fragment_community_page.xml
  app/src/main/res/layout/weather_item.xml
  app/src/main/res/menu/sort_option.xml
Labels: feature

#107 Feature/searchpage image
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sansaninfo/Main/MainActivity.kt
  app/src/main/java/com/example/sansaninfo/Main/MainViewModel.kt
  app/src/main/java/com/example/sansaninfo/SearchPage/SearchPageMountainFragment.kt
  app/src/main/java/com/example/sansaninfo/Util/ConnectWatcher.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_search_page_mountain.xml
Labels: feature, design

#109 [FEAT] : AddPage -> DetailPage
  app/src/main/java/com/example/sansaninfo/AddPage/AddPageActivity.kt
  app/src/main/java/com/example/sansaninfo/CommunityPage/CommunityPageAdapter.kt
  app/src/main/java/com/example/sansaninfo/CommunityPage/CommunityPageFragment.kt
  app/src/main/java/com/example/sansaninfo/DetailPage/DetailPageActivity.kt
  app/src/main/java/com/example/sansaninfo/Main/MainActivity.kt
  app/src/main/java/com/example/sansaninfo/SignPage/SignInActivity.kt
  app/src/main/res/layout/activity_main.xml
Labels: feature

#110 Feature/chatting
  app/src/main/java/com/example/sansaninfo/AddPage/AddPageActivity.kt
  app/src/main/java/com/example/sansaninfo/Chatting/ChattingListFragment.kt
  app/src/main/java/com/example/sansaninfo/Chatting/ChattingPageActivity.kt
  app/src/main/java/com/example/sansaninfo/Chatting/RecyclerChatRoomsAdapter.kt
  app/src/main/java/com/example/sansaninfo/Chatting/RecyclerMessagesAdapter.kt
  app/src/main/java/com/example/sansaninfo/Data/PostModel.kt
  app/src/main/java/com/example/sansaninfo/Data/RoomData.kt
  app/src/main/java/com/example/sansaninfo/Data/UserData.kt
Labels: bug_fix

#111 [Design]: 회원가입 페이지 제목과 자동로그인,이메일 저장 스타일 적용
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/activity_sign_up.xml
Labels: design

#113 [CommunityPage] - 정렬 기능
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/sansaninfo/CommunityPage/CommunityPageFragment.kt
  app/src/main/res/menu/sort_option.xml
Labels: feature

#114 [FEAT] : 1. 수정하기
  app/src/main/java/com/example/sansaninfo/AddPage/AddPageActivity.kt
  app/src/main/java/com/example/sansaninfo/DetailPage/DetailPageActivity.kt
Labels: feature

#118 Feature/chatting
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sansaninfo/AddPage/AddPageActivity.kt
  app/src/main/java/com/example/sansaninfo/Chatting/ChatRoomActivity.kt
  app/src/main/java/com/example/sansaninfo/Chatting/ChatRoomListAdapter.kt
  app/src/main/java/com/example/sansaninfo/Chatting/ChattingListAdapter.kt
  app/src/main/java/com/example/sansaninfo/Chatting/ChattingListFragment.kt
  app/src/main/java/com/example/sansaninfo/Chatting/ChattingModel.kt
  app/src/main/java/com/example/sansaninfo/Chatting/ChattingMsgAdapter.kt
  app/src/main/java/com/example/sansaninfo/Chatting/ChattingPage.kt
  app/src/main/java/com/example/sansaninfo/Chatting/ChattingPageActivity.kt
  app/src/main/java/com/example/sansaninfo/Chatting/MsgListAdapter.kt
  app/src/main/java/com/example/sansaninfo/Chatting/RecyclerChatRoomsAdapter.kt
  app/src/main/java/com/example/sansaninfo/Chatting/RecyclerMessagesAdapter.kt
  app/src/main/java/com/example/sansaninfo/Data/ChatRoom.kt
  app/src/main/java/com/example/sansaninfo/Data/Message.kt
  app/src/main/java/com/example/sansaninfo/Data/MessageData.kt
  app/src/main/java/com/example/sansaninfo/Data/RoomData.kt
  app/src/main/java/com/example/sansaninfo/Data/UserData.kt
  app/src/main/java/com/example/sansaninfo/Data/UserModel.kt
  app/src/main/java/com/example/sansaninfo/Main/MainViewPagerAdapter.kt
  app/src/main/res/layout/fragment_chatting_list.xml
  app/src/main/res/layout/list_talk_item_mine.xml
Labels: feature, remove

#119 [FEAT] : 1. 애드페이지 수정하기 기능
  app/src/main/java/com/example/sansaninfo/AddPage/AddPageActivity.kt
  app/src/main/java/com/example/sansaninfo/DetailPage/DetailPageActivity.kt
  app/src/main/res/drawable/photo.png
Labels: feature

#120 [DetailPage, MyPage, CommunityPage] UI 수정
  app/src/main/res/drawable/ic_handshake_white.xml
  app/src/main/res/drawable/ic_logo_plus_white.xml
  app/src/main/res/layout/activity_detail_page.xml
  app/src/main/res/layout/fragment_community_page.xml
  app/src/main/res/layout/fragment_my_page.xml
Labels: design

#125 Feature/info page enhancement
  app/src/main/java/com/sandamso/sansaninfo/DetailPage/DetailPageActivity.kt
  app/src/main/java/com/sandamso/sansaninfo/SearchPage/MountainMapping.kt
  app/src/main/res/layout/activity_add_page.xml
  app/src/main/res/layout/activity_detail_page.xml
  app/src/main/res/layout/community_page_item.xml
  app/src/main/res/layout/fragment_my_page.xml
Labels: feature, design

#130 Feature/chattingpage
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sandamso/sansaninfo/AddPage/AddPageActivity.kt
  app/src/main/java/com/sandamso/sansaninfo/ChattingPage/ChatRoomActivity.kt
  app/src/main/java/com/sandamso/sansaninfo/ChattingPage/ChatRoomListAdapter.kt
  app/src/main/java/com/sandamso/sansaninfo/ChattingPage/ChattingListFragment.kt
  app/src/main/java/com/sandamso/sansaninfo/ChattingPage/MsgListAdapter.kt
  app/src/main/java/com/sandamso/sansaninfo/Data/RoomData.kt
  app/src/main/java/com/sandamso/sansaninfo/DetailPage/DetailPageActivity.kt
  app/src/main/java/com/sandamso/sansaninfo/Main/MainViewPagerAdapter.kt
  app/src/main/res/layout/fragment_chatting_list.xml
Labels: feature

#131 [feature] : 1. community, add, detail page
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sandamso/sansaninfo/AddPage/AddPageActivity.kt
  app/src/main/java/com/sandamso/sansaninfo/Chatting/MsgListAdapter.kt
  app/src/main/java/com/sandamso/sansaninfo/CommunityPage/CommunityPageAdapter.kt
  app/src/main/java/com/sandamso/sansaninfo/Data/PostModel.kt
  app/src/main/java/com/sandamso/sansaninfo/DetailPage/DetailPageActivity.kt
  app/src/main/java/com/sandamso/sansaninfo/SignPage/SignInActivity.kt
  app/src/main/java/com/sandamso/sansaninfo/SplashScreen.kt
  app/src/main/res/drawable/add_page_stroke_round_rec_err.xml
  app/src/main/res/layout/activity_add_page.xml
  app/src/main/res/layout/activity_detail_page.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/community_page_item.xml
  app/src/main/res/layout/fragment_community_page.xml
Labels: feature

#132 [Info/Community-page] 2차 기능 및 UI 수정 완료
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/src/main/java/com/sandamso/sansaninfo/CommunityPage/CommunityPageFragment.kt
  app/src/main/java/com/sandamso/sansaninfo/InfoPage/InfoPage.kt
  app/src/main/java/com/sandamso/sansaninfo/InfoPage/RegionLocation.kt
  app/src/main/java/com/sandamso/sansaninfo/SearchPage/GooData.kt
  app/src/main/res/drawable/community_page_sort.xml
  app/src/main/res/drawable/ic_crying_emoji.png
  app/src/main/res/layout/activity_info_page.xml
  app/src/main/res/layout/fragment_community_page.xml
  app/src/main/res/menu/sort_option.xml
  app/src/main/res/values/strings.xml
Labels: feature, design

#134 [InfoPage/DetailPage] 지도 정확성 향상, 새로고침 기능 추가
  app/build.gradle
  app/src/main/java/com/sandamso/sansaninfo/DetailPage/DetailPageActivity.kt
  app/src/main/java/com/sandamso/sansaninfo/InfoPage/InfoPage.kt
  app/src/main/res/layout/activity_detail_page.xml
  app/src/main/res/layout/fragment_community_page.xml
Labels: feature, design

#136 Feature/chattingpage
  app/src/main/java/com/sandamso/sansaninfo/AddPage/AddPageActivity.kt
  app/src/main/java/com/sandamso/sansaninfo/Data/RoomData.kt
  app/src/main/java/com/sandamso/sansaninfo/DetailPage/DetailPageActivity.kt
Labels: feature

#139 [FIX] : 🐛 채팅 목록 오류 잡기
  app/src/main/java/com/sandamso/sansaninfo/AddPage/AddPageActivity.kt
  app/src/main/java/com/sandamso/sansaninfo/ChattingPage/ChattingListFragment.kt
  app/src/main/java/com/sandamso/sansaninfo/Data/RoomData.kt
  app/src/main/java/com/sandamso/sansaninfo/DetailPage/DetailPageActivity.kt
  app/src/main/java/com/sandamso/sansaninfo/SignPage/SignInActivity.kt
Labels: bug_fix

#141 [Chatting Page] 채팅 목록 구현하기
  app/src/main/java/com/sandamso/sansaninfo/AddPage/AddPageActivity.kt
  app/src/main/java/com/sandamso/sansaninfo/ChattingPage/ChattingListFragment.kt
  app/src/main/res/layout/fragment_chatting_list.xml
Labels: feature

#143 Feature/info page mnt name
  app/src/main/java/com/sandamso/sansaninfo/AddPage/AddPageActivity.kt
  app/src/main/java/com/sandamso/sansaninfo/DetailPage/DetailPageActivity.kt
  app/src/main/java/com/sandamso/sansaninfo/InfoPage/InfoPage.kt
  app/src/main/res/layout/activity_change_nickname.xml
  app/src/main/res/layout/activity_detail_page.xml
  app/src/main/res/layout/activity_info_page.xml
  app/src/main/res/layout/fragment_chatting_list.xml
  app/src/main/res/layout/fragment_community_page.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_search_page_mountain.xml
Labels: feature, design

#145 [feature] : searchpage
  app/src/main/java/com/sandamso/sansaninfo/Chatting/MsgListAdapter.kt
  app/src/main/java/com/sandamso/sansaninfo/SearchPage/SearchPageMountainFragment.kt
  app/src/main/java/com/sandamso/sansaninfo/SignPage/SignInActivity.kt
  app/src/main/res/layout/activity_change_nickname.xml
Labels: feature

#147 [chatting-page] ViewType 다르게 설정하는 기능 추가
  app/src/main/java/com/sandamso/sansaninfo/ChattingPage/ChatRoomActivity.kt
  app/src/main/java/com/sandamso/sansaninfo/ChattingPage/MsgListAdapter.kt
  app/src/main/res/layout/list_talk_item_mine.xml
  app/src/main/res/layout/list_talk_item_others.xml
Labels: feature, design

#148 [AllPages] UI 수정 (채팅관련 페이지는 아직 좀 더 수정해야함)
  app/src/main/res/drawable/background_talk.xml
  app/src/main/res/drawable/background_talk_mine.xml
  app/src/main/res/drawable/background_talk_others.xml
  app/src/main/res/drawable/chatting_roundbox.xml
  app/src/main/res/drawable/ic_message.xml
  app/src/main/res/layout/activity_add_page.xml
  app/src/main/res/layout/activity_chatting_page.xml
  app/src/main/res/layout/activity_findpw_result.xml
  app/src/main/res/layout/activity_info_page.xml
  app/src/main/res/layout/chatting_list_item.xml
  app/src/main/res/layout/fragment_chatting_list.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_search_page_mountain.xml
  app/src/main/res/layout/list_talk_item_mine.xml
  app/src/main/res/layout/list_talk_item_others.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: design

#151 [Chatting-page] viewType 작업수정완료
  app/src/main/java/com/sandamso/sansaninfo/ChattingPage/ChatRoomActivity.kt
  app/src/main/java/com/sandamso/sansaninfo/ChattingPage/MsgListAdapter.kt
Labels: feature

#153 [Toast Message] 디자인 변경
  app/src/main/java/com/sandamso/sansaninfo/AddPage/AddPageActivity.kt
  app/src/main/java/com/sandamso/sansaninfo/BaseActivity.kt
  app/src/main/java/com/sandamso/sansaninfo/DetailPage/DetailPageActivity.kt
  app/src/main/java/com/sandamso/sansaninfo/InfoPage/InfoPage.kt
  app/src/main/java/com/sandamso/sansaninfo/MyPage/ChangeNicknameActivity.kt
  app/src/main/java/com/sandamso/sansaninfo/MyPage/MyPageFragment.kt
  app/src/main/java/com/sandamso/sansaninfo/SignPage/FindpwActivity.kt
  app/src/main/java/com/sandamso/sansaninfo/SignPage/SignInActivity.kt
  app/src/main/java/com/sandamso/sansaninfo/SignPage/SignUpActivity.kt
  app/src/main/res/drawable/background_toast.xml
  app/src/main/res/drawable/ic_logo_msg.xml
  app/src/main/res/layout/toast_msg.xml
Labels: design

#155 [Dday] CommunityPage, DetailPage
  app/src/main/java/com/sandamso/sansaninfo/CommunityPage/CommunityPageAdapter.kt
  app/src/main/java/com/sandamso/sansaninfo/DetailPage/DetailPageActivity.kt
Labels: feature

#157 로그인 부분 기능 검토 및 수정
  app/build.gradle
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sandamso/sansaninfo/GlobalApplication.kt
  app/src/main/java/com/sandamso/sansaninfo/MyPage/MyPageFragment.kt
  app/src/main/java/com/sandamso/sansaninfo/SignPage/SignInActivity.kt
  app/src/main/java/com/sandamso/sansaninfo/SplashScreen.kt
  app/src/main/res/drawable/background_toast.xml
  app/src/main/res/layout/activity_chatting_page.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/values/strings.xml
  build.gradle
  settings.gradle
Labels: bug_fix, design

#160 채팅 알람 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sandamso/sansaninfo/ChattingPage/ChatRoomActivity.kt
Labels: feature

#161 [Community, Search-page] 스피너 기능 수정완료
  app/src/main/java/com/sandamso/sansaninfo/CommunityPage/CommunityPageFragment.kt
  app/src/main/java/com/sandamso/sansaninfo/Main/MainActivity.kt
  app/src/main/java/com/sandamso/sansaninfo/Main/MainTab.kt
  app/src/main/java/com/sandamso/sansaninfo/Main/MainViewPagerAdapter.kt
  app/src/main/java/com/sandamso/sansaninfo/SearchPage/SearchPageMountainFragment.kt
Labels: feature

#163 [ChattingPage] 채팅 말풍선 수정
  app/src/main/java/com/sandamso/sansaninfo/ChattingPage/MsgListAdapter.kt
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/list_talk_item_mine.xml
  app/src/main/res/layout/list_talk_item_others.xml
Labels: feature, design

#167 [FEAT] : ⚙️ 채팅방 나가기 기능 구현
  app/src/main/java/com/sandamso/sansaninfo/ChattingPage/ChatRoomListAdapter.kt
  app/src/main/java/com/sandamso/sansaninfo/ChattingPage/ChattingListFragment.kt
Labels: feature

#169 [LITTLE_FIX] : 🔧 로딩 중 프로그래스 바만 보이게 구현하기
  app/src/main/java/com/sandamso/sansaninfo/AddPage/AddPageActivity.kt
  app/src/main/res/layout/activity_add_page.xml
Labels: little_fix

#171 [Community-page] 정렬기능 수정하기
  app/src/main/java/com/sandamso/sansaninfo/CommunityPage/CommunityPageFragment.kt
  app/src/main/res/values/strings.xml
Labels: feature

#172 [ChattingPage] 시간 알림 띄우는중
  app/src/main/java/com/sandamso/sansaninfo/ChattingPage/ChattingListFragment.kt
  app/src/main/res/drawable/background_talk_enter.xml
  app/src/main/res/layout/activity_add_page.xml
  app/src/main/res/layout/activity_change_nickname.xml
  app/src/main/res/layout/activity_chatting_page.xml
  app/src/main/res/layout/list_talk_item_enter.xml
  app/src/main/res/values-night/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: feature, design

#175 참여하기 버튼 비활성화
  app/src/main/java/com/sandamso/sansaninfo/DetailPage/DetailPageActivity.kt
  app/src/main/res/layout/activity_info_page.xml
Labels: feature, design

#177 [FEAT] : ⚙️: chattingRoomList에 새로운 메세지 알림표시 (현재 진행중)
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/sandamso/sansaninfo/AddPage/AddPageActivity.kt
  app/src/main/java/com/sandamso/sansaninfo/ChattingPage/ChatRoomActivity.kt
  app/src/main/java/com/sandamso/sansaninfo/ChattingPage/ChattingListAdapter.kt
  app/src/main/java/com/sandamso/sansaninfo/ChattingPage/ChattingListFragment.kt
  app/src/main/res/drawable/background_talk.xml
  app/src/main/res/layout/chatting_list_item.xml
Labels: feature

#181 [FEAT] : ⚙️: 커뮤니티 페이지 참여한 인원 수 정보 제공
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sandamso/sansaninfo/SplashScreen.kt
  app/src/main/java/com/sandamso/sansaninfo/chattingpage/ChattingListFragment.kt
  app/src/main/java/com/sandamso/sansaninfo/detailpage/DetailPageActivity.kt
  app/src/main/java/com/sandamso/sansaninfo/mypage/MyPageFragment.kt
  app/src/main/res/layout/activity_findpw.xml
  app/src/main/res/layout/activity_findpw_result.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/community_page_item.xml
Labels: feature

#182 [REFACTOR]: 패키지명 수정
  app/src/main/java/com/sandamso/sansaninfo/signpage/FindpwActivity.kt
  app/src/main/java/com/sandamso/sansaninfo/signpage/FindpwResultActivity.kt
  app/src/main/java/com/sandamso/sansaninfo/signpage/SignInActivity.kt
  app/src/main/java/com/sandamso/sansaninfo/signpage/SignUpActivity.kt
  app/src/main/java/com/sandamso/sansaninfo/signpage/SignUpDialog.kt
Labels: feature

#184 [Feature] 채팅관련 기능 수정 및 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sandamso/sansaninfo/UserPopUp.kt
  app/src/main/java/com/sandamso/sansaninfo/addpage/AddPageActivity.kt
  app/src/main/java/com/sandamso/sansaninfo/chattingpage/ChatRoomActivity.kt
  app/src/main/java/com/sandamso/sansaninfo/chattingpage/ChattingListAdapter.kt
  app/src/main/java/com/sandamso/sansaninfo/chattingpage/ChattingListFragment.kt
  app/src/main/java/com/sandamso/sansaninfo/communitypage/CommunityPageAdapter.kt
  app/src/main/java/com/sandamso/sansaninfo/data/PostModel.kt
  app/src/main/java/com/sandamso/sansaninfo/data/RoomData.kt
  app/src/main/java/com/sandamso/sansaninfo/detailpage/DetailPageActivity.kt
  app/src/main/res/drawable/btn_desert_borderless2.xml
  app/src/main/res/layout/activity_chatting_page.xml
  app/src/main/res/layout/activity_user_pop_up.xml
  app/src/main/res/layout/chatting_list_item.xml
  app/src/main/res/values/strings.xml
Labels: bug_fix, feature, design, little_fix

#186 [Community-page] 인기순 정렬 기능 구현완료
  app/src/main/java/com/sandamso/sansaninfo/communitypage/CommunityPageFragment.kt
Labels: feature

#189 App Icon 만들기 🎨
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
Labels: design

#190 [TutorialPage] 이미지 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sandamso/sansaninfo/TutorialActivity/TutorialActivity.kt
  app/src/main/java/com/sandamso/sansaninfo/communitypage/CommunityPageFragment.kt
  app/src/main/res/drawable/tutorial01.png
  app/src/main/res/drawable/tutorial02.png
  app/src/main/res/drawable/tutorial03.png
  app/src/main/res/drawable/tutorial04.png
  app/src/main/res/drawable/tutorial05.png
  app/src/main/res/drawable/tutorial06.png
  app/src/main/res/drawable/tutorial07.png
  app/src/main/res/drawable/tutorial08.png
  app/src/main/res/layout-night/activity_chatting_page.xml
  app/src/main/res/layout-night/activity_info_page.xml
  app/src/main/res/layout/activity_detail_page.xml
  app/src/main/res/layout/activity_info_page.xml
  app/src/main/res/layout/activity_tutorial.xml
  app/src/main/res/layout/fragment_my_page.xml
Labels: feature, design

#192 [FEAT] : ⚙️: 튜토리얼 페이지추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sandamso/sansaninfo/SplashScreen.kt
  app/src/main/java/com/sandamso/sansaninfo/TutorialActivity/TutorialActivity.kt
  app/src/main/java/com/sandamso/sansaninfo/mypage/MyPageFragment.kt
  app/src/main/res/drawable/tutorial01.png
  app/src/main/res/drawable/tutorial02.png
  app/src/main/res/drawable/tutorial03.png
  app/src/main/res/drawable/tutorial04.png
  app/src/main/res/drawable/tutorial05.png
  app/src/main/res/drawable/tutorial06.png
  app/src/main/res/drawable/tutorial07.png
  app/src/main/res/drawable/tutorial08.png
  app/src/main/res/layout/activity_tutorial.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/values/strings.xml
Labels: feature

#194 [Feature, Fix] 채팅방 관련 오류 수정 및 기능 추가
  app/src/main/java/com/sandamso/sansaninfo/chattingpage/ChatRoomActivity.kt
  app/src/main/java/com/sandamso/sansaninfo/chattingpage/ChattingListAdapter.kt
  app/src/main/java/com/sandamso/sansaninfo/chattingpage/ChattingListFragment.kt
  app/src/main/java/com/sandamso/sansaninfo/detailpage/DetailPageActivity.kt
  app/src/main/java/com/sandamso/sansaninfo/signpage/SignInActivity.kt
  app/src/main/res/layout/activity_user_pop_up.xml
Labels: bug_fix, feature

#195 [FEAT] : ⚙️: 회원 탈퇴 기능 추가
  app/src/main/java/com/sandamso/sansaninfo/chattingpage/ChattingListFragment.kt
  app/src/main/java/com/sandamso/sansaninfo/mypage/MyPageFragment.kt
Labels: feature
