Repository palzo/sandamso, pull requests merged in 2023-10, with the labels that each got.

#3 [DESIGN] : 🎨 로그인 & 회원가입 페이지 ui 틀 구현
  app/src/main/java/com/example/sansaninfo/Fragment/SignInFragment.kt
  app/src/main/java/com/example/sansaninfo/Fragment/SignUpFragment.kt
  app/src/main/res/layout/fragment_sign_in.xml
  app/src/main/res/layout/fragment_sign_up.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: design

#4 Feature/firebase 로그인 및 회원가입 연결
  .idea/deploymentTargetDropDown.xml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/vcs.xml
  app/build.gradle
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sansaninfo/Activity/SignInActivity.kt
  app/src/main/java/com/example/sansaninfo/Activity/SignUpActivity.kt
  app/src/main/java/com/example/sansaninfo/Data/UserData.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: feature

#12 [DESIGN] : 🎨: 이미지 추가
  app/src/main/res/drawable/ic_ad_banner.xml
  app/src/main/res/drawable/ic_add_photo.xml
  app/src/main/res/drawable/ic_back_arrow.xml
  app/src/main/res/drawable/ic_cloud.xml
  app/src/main/res/drawable/ic_darkmode.xml
  app/src/main/res/drawable/ic_down_direction.xml
  app/src/main/res/drawable/ic_gallery.xml
  app/src/main/res/drawable/ic_gallery2.xml
  app/src/main/res/drawable/ic_gallery_mint.xml
  app/src/main/res/drawable/ic_handshake.xml
  app/src/main/res/drawable/ic_handshake_pink.xml
  app/src/main/res/drawable/ic_heavyrain.xml
  app/src/main/res/drawable/ic_hiker.xml
  app/src/main/res/drawable/ic_hiker_mint.xml
  app/src/main/res/drawable/ic_kakao.xml
  app/src/main/res/drawable/ic_left_direction.xml
  app/src/main/res/drawable/ic_lightmode.xml
  app/src/main/res/drawable/ic_location.xml
  app/src/main/res/drawable/ic_logo.xml
  app/src/main/res/drawable/ic_me.xml
  app/src/main/res/drawable/ic_megaphone.xml
  app/src/main/res/drawable/ic_megaphone_mint.xml
  app/src/main/res/drawable/ic_mist.xml
  app/src/main/res/drawable/ic_mountain.xml
  app/src/main/res/drawable/ic_night.xml
  app/src/main/res/drawable/ic_open_kakao.xml
  app/src/main/res/drawable/ic_option.xml
  app/src/main/res/drawable/ic_pen.xml
  app/src/main/res/drawable/ic_plus.xml
  app/src/main/res/drawable/ic_question.xml
  app/src/main/res/drawable/ic_right_direction.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/ic_search_mint.xml
  app/src/main/res/drawable/ic_snow.xml
  app/src/main/res/drawable/ic_squirrel.xml
  app/src/main/res/drawable/ic_sunny.xml
  app/src/main/res/drawable/ic_thunder.xml
  app/src/main/res/drawable/ic_trash.xml
Labels: design

#13 Design/addcommunity page
  app/src/main/res/drawable/add_page_filled_round_rec.xml
  app/src/main/res/drawable/add_page_mint_button.xml
  app/src/main/res/drawable/add_page_stroke_round_rec.xml
  app/src/main/res/drawable/community_page_item_opercity.xml
  app/src/main/res/drawable/ic_ad_banner.xml
  app/src/main/res/drawable/ic_kakao.xml
  app/src/main/res/drawable/ic_mountain.xml
  app/src/main/res/layout/activity_add_page.xml
  app/src/main/res/layout/community_page_item.xml
  app/src/main/res/layout/fragment_community_page.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: design

#14 [DESIGN] : 🎨: mypage, infopage
  app/src/main/java/com/example/sansaninfo/InfoPage/InfoPage.kt
  app/src/main/res/layout/activity_info_page.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/weather_item.xml
  app/src/main/res/values/strings.xml
Labels: design

#16 Design/detail
  app/src/main/java/com/example/sansaninfo/SearchPage/SearchPageMountainFragment.kt
  app/src/main/java/com/example/sansaninfo/SearchPage/SearchPageRegionFragment.kt
  app/src/main/res/drawable/detail_page_background.xml
  app/src/main/res/drawable/detail_page_talk_background.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/img_mountain.png
  app/src/main/res/drawable/photo.png
  app/src/main/res/drawable/search_page_background.xml
  app/src/main/res/drawable/search_page_button_background.xml
  app/src/main/res/drawable/search_page_click_button_background.xml
  app/src/main/res/layout/activity_detail_page.xml
  app/src/main/res/layout/fragment_search_page_mountain.xml
  app/src/main/res/layout/fragment_search_page_region.xml
Labels: design

#19 [FEAT] : ⚙️: tablayout fragment연결
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sansaninfo/AddPage/AddPage.kt
  app/src/main/java/com/example/sansaninfo/CommunityPage/CommunityPageFragment.kt
  app/src/main/java/com/example/sansaninfo/Main/MainActivity.kt
  app/src/main/java/com/example/sansaninfo/Main/MainTab.kt
  app/src/main/java/com/example/sansaninfo/Main/MainViewPagerAdapter.kt
  app/src/main/java/com/example/sansaninfo/MainActivity.kt
  app/src/main/java/com/example/sansaninfo/MyPage/MyPageFragment.kt
  app/src/main/java/com/example/sansaninfo/SearchPage/SearchPageMountainFragment.kt
  app/src/main/java/com/example/sansaninfo/SearchPage/SearchPageRegionFragment.kt
  app/src/main/java/com/example/sansaninfo/SignPage/SignInActivity.kt
  app/src/main/java/com/example/sansaninfo/SignPage/SignUpActivity.kt
  app/src/main/res/layout/activity_detail_page.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/fragment_community_page.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/menu/tabs.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: feature

#25 Feature/weather api
  app/src/main/java/com/example/sansaninfo/AddPage/AddPage.kt
  app/src/main/res/layout/activity_add_page.xml
Labels: documentation

#26 [FEAT] : ⚙️: mountain info data 추가
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sansaninfo/InfoPage/InfoPage.kt
  app/src/main/java/com/example/sansaninfo/MountainInfoData/ApiClient.kt
  app/src/main/java/com/example/sansaninfo/MountainInfoData/ApiService.kt
  app/src/main/java/com/example/sansaninfo/MountainInfoData/Body.kt
  app/src/main/java/com/example/sansaninfo/MountainInfoData/Header.kt
  app/src/main/java/com/example/sansaninfo/MountainInfoData/Hkngpntdscrt.kt
  app/src/main/java/com/example/sansaninfo/MountainInfoData/Item.kt
  app/src/main/java/com/example/sansaninfo/MountainInfoData/Items.kt
  app/src/main/java/com/example/sansaninfo/MountainInfoData/MountainData.kt
  app/src/main/java/com/example/sansaninfo/MountainInfoData/Ptmntrcmmncoursdscrt.kt
  app/src/main/java/com/example/sansaninfo/MountainInfoData/Response.kt
  app/src/main/java/com/example/sansaninfo/MountainInfoData/Script.kt
  app/src/main/res/layout/activity_info_page.xml
  app/src/main/res/values/strings.xml
Labels: feature

#31 [Feature] 회원탈퇴, 로그아웃
  app/src/main/java/com/example/sansaninfo/MyPage/MyPageFragment.kt
  app/src/main/res/layout/fragment_my_page.xml
Labels: feature

#32 Feature/verifyemail
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sansaninfo/SignPage/FindpwActivity.kt
  app/src/main/java/com/example/sansaninfo/SignPage/FindpwResultActivity.kt
  app/src/main/java/com/example/sansaninfo/SignPage/SignInActivity.kt
  app/src/main/java/com/example/sansaninfo/SignPage/SignUpActivity.kt
  app/src/main/res/drawable/findpw_box.xml
  app/src/main/res/layout/activity_findpw.xml
  app/src/main/res/layout/activity_findpw_result.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/values/colors.xml
Labels: feature

#34 Feature/signin up validation
  app/src/main/java/com/example/sansaninfo/SignPage/SignInActivity.kt
  app/src/main/java/com/example/sansaninfo/SignPage/SignUpActivity.kt
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/activity_sign_up.xml
Labels: feature

#35 Feature/communitypage
  app/build.gradle
  app/src/main/java/com/example/sansaninfo/AddPage/AddPage.kt
  app/src/main/java/com/example/sansaninfo/CommunityPage/CommunityPageAdapter.kt
  app/src/main/java/com/example/sansaninfo/CommunityPage/CommunityPageFragment.kt
  app/src/main/java/com/example/sansaninfo/Data/FBRef.kt
  app/src/main/java/com/example/sansaninfo/Data/UserModel.kt
  app/src/main/java/com/example/sansaninfo/DetailPage/DetailPage.kt
  app/src/main/res/layout/activity_add_page.xml
  app/src/main/res/layout/fragment_community_page.xml
Labels: feature

#36 Feature/mountaininfoapi
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sansaninfo/MountainInfoData/ApiClient.kt
  app/src/main/java/com/example/sansaninfo/MountainInfoData/ApiService.kt
  app/src/main/java/com/example/sansaninfo/MountainInfoData/Body.kt
  app/src/main/java/com/example/sansaninfo/MountainInfoData/Header.kt
  app/src/main/java/com/example/sansaninfo/MountainInfoData/Hkngpntdscrt.kt
  app/src/main/java/com/example/sansaninfo/MountainInfoData/Item.kt
  app/src/main/java/com/example/sansaninfo/MountainInfoData/Items.kt
  app/src/main/java/com/example/sansaninfo/MountainInfoData/MountainDTO.kt
  app/src/main/java/com/example/sansaninfo/MountainInfoData/MountainData.kt
  app/src/main/java/com/example/sansaninfo/MountainInfoData/Ptmntrcmmncoursdscrt.kt
  app/src/main/java/com/example/sansaninfo/MountainInfoData/Response.kt
  app/src/main/java/com/example/sansaninfo/MountainInfoData/Script.kt
  app/src/main/java/com/example/sansaninfo/SearchPage/SearchPage.kt
  app/src/main/java/com/example/sansaninfo/SearchPage/SearchPageAdapter.kt
  app/src/main/java/com/example/sansaninfo/SearchPage/SearchPageMountainFragment.kt
  app/src/main/java/com/example/sansaninfo/SearchPage/SearchPageRegionFragment.kt
  app/src/main/res/drawable/search_page_button_background.xml
  app/src/main/res/drawable/search_page_click_button_background.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_search_page.xml
  app/src/main/res/layout/fragment_search_page_mountain.xml
  app/src/main/res/layout/fragment_search_page_region.xml
  app/src/main/res/layout/searchpage_item.xml
  app/src/main/res/values/strings.xml
Labels: feature

#37 Feature/mypage, infopage
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sansaninfo/InfoPage/InfoPage.kt
  app/src/main/java/com/example/sansaninfo/MyPage/ChangeNicknameActivity.kt
  app/src/main/java/com/example/sansaninfo/MyPage/MyPageFragment.kt
  app/src/main/res/layout/activity_change_nickname.xml
  app/src/main/res/layout/activity_info_page.xml
  app/src/main/res/layout/fragment_my_page.xml
Labels: feature, design

#41 Feature/communitypage
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sansaninfo/AddPage/AddPage.kt
  app/src/main/java/com/example/sansaninfo/DetailPage/DetailPage.kt
Labels: feature

#44 Feature/mypage
  app/src/main/java/com/example/sansaninfo/Data/UserData.kt
  app/src/main/java/com/example/sansaninfo/InfoPage/InfoPage.kt
  app/src/main/java/com/example/sansaninfo/MyPage/ChangeNicknameActivity.kt
  app/src/main/java/com/example/sansaninfo/MyPage/MyPageFragment.kt
  app/src/main/res/layout/fragment_my_page.xml
Labels: feature

#45 [FEAT] : ⚙️: 지역명으로 검색 기능 추가
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sansaninfo/InfoPage/InfoPage.kt
  app/src/main/java/com/example/sansaninfo/MountainInfoData/ApiService.kt
  app/src/main/java/com/example/sansaninfo/SearchPage/MountainMapping.kt
  app/src/main/java/com/example/sansaninfo/SearchPage/SearchPageMountainFragment.kt
  app/src/main/res/drawable/powerspinner_bar.xml
  app/src/main/res/layout/fragment_search_page_mountain.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: feature

#47 Feature/communitypage
  app/src/main/java/com/example/sansaninfo/CommunityPage/CommunityPageAdapter.kt
  app/src/main/java/com/example/sansaninfo/CommunityPage/CommunityPageFragment.kt
  app/src/main/java/com/example/sansaninfo/DetailPage/DetailPage.kt
  app/src/main/java/com/example/sansaninfo/SearchPage/SearchPageMountainFragment.kt
  app/src/main/res/layout/community_page_item.xml
  app/src/main/res/layout/fragment_community_page.xml
Labels: feature

#49 Frature/searchpagespinner
  app/src/main/java/com/example/sansaninfo/InfoPage/InfoPage.kt
  app/src/main/java/com/example/sansaninfo/MountainInfoData/ApiService.kt
  app/src/main/java/com/example/sansaninfo/SearchPage/GooData.kt
  app/src/main/java/com/example/sansaninfo/SearchPage/SearchPageMountainFragment.kt
  app/src/main/res/layout/fragment_search_page_mountain.xml
Labels: feature

#50 Feature/info page map
  app/src/main/java/com/example/sansaninfo/InfoPage/InfoPage.kt
  app/src/main/java/com/example/sansaninfo/MyPage/MyPageFragment.kt
Labels: feature

#51 Feature/communitypage
  app/src/main/java/com/example/sansaninfo/AddPage/AddPage.kt
  app/src/main/java/com/example/sansaninfo/CommunityPage/CommunityPageFragment.kt
  app/src/main/java/com/example/sansaninfo/DetailPage/DetailPage.kt
  app/src/main/res/drawable/ic_add_photo.xml
  app/src/main/res/layout/activity_add_page.xml
  app/src/main/res/layout/activity_detail_page.xml
Labels: feature, design

#52 Feature/weatherapi
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/com/example/sansaninfo/API/Constrants/Constrant.kt
  app/src/main/java/com/example/sansaninfo/API/ModelData/RegionLocation.kt
  app/src/main/java/com/example/sansaninfo/API/ModelData/WeatherModel.kt
  app/src/main/java/com/example/sansaninfo/API/Retrofit/WeatherClient.kt
  app/src/main/java/com/example/sansaninfo/API/Retrofit/WeatherInterface.kt
  app/src/main/java/com/example/sansaninfo/InfoPage/InfoPage.kt
  app/src/main/java/com/example/sansaninfo/InfoPage/InfoPageAdapter.kt
  app/src/main/java/com/example/sansaninfo/InfoPage/WeatherData.kt
Labels: feature

#58 Feature/searchinfopage
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sansaninfo/InfoPage/InfoPage.kt
  app/src/main/java/com/example/sansaninfo/MountainImageAPI/MntImgClient.kt
  app/src/main/java/com/example/sansaninfo/MountainImageAPI/MntImgDTO.kt
  app/src/main/java/com/example/sansaninfo/MountainImageAPI/MntImgService.kt
  app/src/main/java/com/example/sansaninfo/MountainInfoAPI/ApiClient.kt
  app/src/main/java/com/example/sansaninfo/MountainInfoAPI/ApiService.kt
  app/src/main/java/com/example/sansaninfo/MountainInfoAPI/MountainDTO.kt
  app/src/main/java/com/example/sansaninfo/SearchPage/MountainMapping.kt
  app/src/main/java/com/example/sansaninfo/SearchPage/SearchPageAdapter.kt
  app/src/main/java/com/example/sansaninfo/SearchPage/SearchPageMountainFragment.kt
  app/src/main/java/com/example/sansaninfo/SplashScreen.kt
  app/src/main/res/anim/slide_down_enter.xml
  app/src/main/res/anim/slide_down_exit.xml
  app/src/main/res/anim/slide_left_enter.xml
  app/src/main/res/anim/slide_left_exit.xml
  app/src/main/res/anim/slide_right_enter.xml
  app/src/main/res/anim/slide_right_exit.xml
  app/src/main/res/drawable/ic_mnt1.png
  app/src/main/res/drawable/ic_mnt10.png
  app/src/main/res/drawable/ic_mnt11.png
  app/src/main/res/drawable/ic_mnt12.png
  app/src/main/res/drawable/ic_mnt13.png
  app/src/main/res/drawable/ic_mnt14.png
  app/src/main/res/drawable/ic_mnt15.png
  app/src/main/res/drawable/ic_mnt16.png
  app/src/main/res/drawable/ic_mnt17.png
  app/src/main/res/drawable/ic_mnt18.png
  app/src/main/res/drawable/ic_mnt19.png
  app/src/main/res/drawable/ic_mnt2.png
  app/src/main/res/drawable/ic_mnt20.png
  app/src/main/res/drawable/ic_mnt21.png
  app/src/main/res/drawable/ic_mnt22.png
  app/src/main/res/drawable/ic_mnt23.png
  app/src/main/res/drawable/ic_mnt24.png
  app/src/main/res/drawable/ic_mnt25.png
  app/src/main/res/drawable/ic_mnt26.png
  app/src/main/res/drawable/ic_mnt3.png
  app/src/main/res/drawable/ic_mnt4.png
  app/src/main/res/drawable/ic_mnt5.png
  app/src/main/res/drawable/ic_mnt6.png
  app/src/main/res/drawable/ic_mnt7.png
  app/src/main/res/drawable/ic_mnt8.png
  app/src/main/res/drawable/ic_mnt9.png
  app/src/main/res/drawable/ic_splash.png
  app/src/main/res/layout/activity_splash_screen.xml
  app/src/main/res/layout/searchpage_item.xml
Labels: feature

#61 Feature/communitypage
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sansaninfo/AddPage/AddPage.kt
  app/src/main/java/com/example/sansaninfo/CommunityPage/CommunityPageAdapter.kt
  app/src/main/java/com/example/sansaninfo/CommunityPage/CommunityPageFragment.kt
  app/src/main/java/com/example/sansaninfo/Data/PostModel.kt
  app/src/main/java/com/example/sansaninfo/DetailPage/DetailPage.kt
  app/src/main/res/drawable/ic_plus.xml
  app/src/main/res/layout/activity_add_page.xml
  app/src/main/res/layout/community_page_item.xml
  app/src/main/res/layout/fragment_community_page.xml
Labels: feature

#62 Feature/info weather
  app/src/main/java/com/example/sansaninfo/API/Constrants/Constrant.kt
  app/src/main/java/com/example/sansaninfo/API/ModelData/RegionLocation.kt
  app/src/main/java/com/example/sansaninfo/API/ModelData/WeatherModel.kt
  app/src/main/java/com/example/sansaninfo/API/Retrofit/WeatherClient.kt
  app/src/main/java/com/example/sansaninfo/API/Retrofit/WeatherInterface.kt
  app/src/main/java/com/example/sansaninfo/InfoPage/InfoPage.kt
  app/src/main/java/com/example/sansaninfo/InfoPage/InfoPageAdapter.kt
  app/src/main/java/com/example/sansaninfo/InfoPage/WeatherData.kt
  app/src/main/res/drawable/signin_et_border.xml
  app/src/main/res/drawable/signin_roundbox.xml
  app/src/main/res/drawable/signup_et_border.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/searchpage_item.xml
  app/src/main/res/layout/weather_item.xml
Labels: feature, design

#64 Feature/info map coroutine
  app/src/main/java/com/example/sansaninfo/InfoPage/InfoPage.kt
  app/src/main/res/drawable/add_photo.xml
  app/src/main/res/layout/activity_add_page.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/searchpage_item.xml
Labels: feature, design

#65 [FEAT] : ⚙️: searchpage
  app/src/main/java/com/example/sansaninfo/InfoPage/InfoPage.kt
  app/src/main/java/com/example/sansaninfo/MountainInfoAPI/MountainDTO.kt
  app/src/main/java/com/example/sansaninfo/SearchPage/SearchPageAdapter.kt
  app/src/main/java/com/example/sansaninfo/SearchPage/SearchPageMountainFragment.kt
  app/src/main/java/com/example/sansaninfo/SignPage/SignInActivity.kt
  app/src/main/java/com/example/sansaninfo/SplashScreen.kt
  app/src/main/res/layout/activity_info_page.xml
Labels: feature

#66 Feature/communitypage
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sansaninfo/AddPage/AddPageActivity.kt
  app/src/main/java/com/example/sansaninfo/CommunityPage/CommunityPageAdapter.kt
  app/src/main/java/com/example/sansaninfo/CommunityPage/CommunityPageFragment.kt
  app/src/main/java/com/example/sansaninfo/DetailPage/DetailPageActivity.kt
  app/src/main/java/com/example/sansaninfo/SplashScreen.kt
  app/src/main/res/anim/fade_in.xml
  app/src/main/res/anim/fade_out.xml
  app/src/main/res/layout/activity_add_page.xml
  app/src/main/res/layout/activity_detail_page.xml
  app/src/main/res/layout/activity_splash_screen.xml
Labels: feature

#68 [FIX] : 🐛: 잔잔바리 수정
  app/src/main/java/com/example/sansaninfo/AddPage/AddPageActivity.kt
  app/src/main/res/layout/activity_detail_page.xml
Labels: enhancement

#71 UI/detailpage
  app/src/main/res/layout/activity_detail_page.xml
  app/src/main/res/layout/community_page_item.xml
Labels: design

#72 [FIX] : 🐛: 잔잔바리 수정
  app/src/main/res/layout/community_page_item.xml
Labels: design

#76 [로그인페이지] 소셜 로그인 기능
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sansaninfo/MyPage/MyPageFragment.kt
  app/src/main/java/com/example/sansaninfo/SearchPage/SearchPageMountainFragment.kt
  app/src/main/java/com/example/sansaninfo/SignPage/SignInActivity.kt
  app/src/main/res/drawable/signin_btn_kakao.png
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/searchpage_item.xml
  settings.gradle
Labels: feature

#78 feature/addpage
  app/src/main/java/com/example/sansaninfo/AddPage/AddPageActivity.kt
  app/src/main/java/com/example/sansaninfo/CommunityPage/CommunityPageAdapter.kt
  app/src/main/java/com/example/sansaninfo/CommunityPage/CommunityPageFragment.kt
  app/src/main/java/com/example/sansaninfo/Data/PostModel.kt
  app/src/main/java/com/example/sansaninfo/DetailPage/DetailPageActivity.kt
  app/src/main/res/drawable/calendar.xml
  app/src/main/res/layout/activity_add_page.xml
  app/src/main/res/layout/activity_detail_page.xml
  app/src/main/res/layout/community_page_item.xml
Labels: feature

#79 [FEAT] : 1. GlobalApplication.kt 파일 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sansaninfo/GlobalApplication.kt
  app/src/main/res/drawable/signin_btn_kakao.xml
  app/src/main/res/layout/activity_info_page.xml
Labels: feature
